version: '3.4'
services:
  db:
    image: mariadb
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: dsus
        MYSQL_USER: ontop
        MYSQL_PASSWORD: ontop
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  ontop:
    image: ontop/ontop
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/ontology-for-bariatric-surgery.owl
      ONTOP_MAPPING_FILE: /opt/ontop/input/ontology-for-bariatric-surgery.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/ontology-for-bariatric-surgery.properties
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      ONTOP_LAZY_INIT: "true"
    volumes:
      - ./input:/opt/ontop/input
      - ./ontop/jdbc:/opt/ontop/jdbc
    ports:
      - "8080:8080"

